#include <tchar.h>

void ListDrivers(void);
void ExamineDriver(TCHAR* name);
void BruteforceCodes(TCHAR *name);
void ConvertCode(unsigned int code);

#define MAX_FUNCTION_CODE 0x1000
#define ARRAY_SIZE 1024
#define DEVICE_TYPE_COUNT 57
TCHAR* device_types[DEVICE_TYPE_COUNT] = {
	_T("FILE_DEVICE_BEEP"),
	_T("FILE_DEVICE_CD_ROM"),
	_T("FILE_DEVICE_CD_ROM_FILE_SYSTEM"),
	_T("FILE_DEVICE_CONTROLLER"),
	_T("FILE_DEVICE_DATALINK"),
	_T("FILE_DEVICE_DFS"),
	_T("FILE_DEVICE_DISK"),
	_T("FILE_DEVICE_DISK_FILE_SYSTEM"),
	_T("FILE_DEVICE_FILE_SYSTEM"),
	_T("FILE_DEVICE_INPORT_PORT"),
	_T("FILE_DEVICE_KEYBOARD"),
	_T("FILE_DEVICE_MAILSLOT"),
	_T("FILE_DEVICE_MIDI_IN"),
	_T("FILE_DEVICE_MIDI_OUT"),
	_T("FILE_DEVICE_MOUSE"),
	_T("FILE_DEVICE_MULTI_UNC_PROVIDER"),
	_T("FILE_DEVICE_NAMED_PIPE"),
	_T("FILE_DEVICE_NETWORK"),
	_T("FILE_DEVICE_NETWORK_BROWSER"),
	_T("FILE_DEVICE_NETWORK_FILE_SYSTEM"),
	_T("FILE_DEVICE_NULL"),
	_T("FILE_DEVICE_PARALLEL_PORT"),
	_T("FILE_DEVICE_PHYSICAL_NETCARD"),
	_T("FILE_DEVICE_PRINTER"),
	_T("FILE_DEVICE_SCANNER"),
	_T("FILE_DEVICE_SERIAL_MOUSE_PORT"),
	_T("FILE_DEVICE_SERIAL_PORT"),
	_T("FILE_DEVICE_SCREEN"),
	_T("FILE_DEVICE_SOUND"),
	_T("FILE_DEVICE_STREAMS"),
	_T("FILE_DEVICE_TAPE"),
	_T("FILE_DEVICE_TAPE_FILE_SYSTEM"),
	_T("FILE_DEVICE_TRANSPORT"),
	_T("FILE_DEVICE_UNKNOWN"),
	_T("FILE_DEVICE_VIDEO"),
	_T("FILE_DEVICE_VIRTUAL_DISK"),
	_T("FILE_DEVICE_WAVE_IN"),
	_T("FILE_DEVICE_WAVE_OUT"),
	_T("FILE_DEVICE_8042_PORT"),
	_T("FILE_DEVICE_NETWORK_REDIRECTOR"),
	_T("FILE_DEVICE_BATTERY"),
	_T("FILE_DEVICE_BUS_EXTENDER"),
	_T("FILE_DEVICE_MODEM"),
	_T("FILE_DEVICE_VDM"),
	_T("FILE_DEVICE_MASS_STORAGE"),
	_T("FILE_DEVICE_SMB"),
	_T("FILE_DEVICE_KS"),
	_T("FILE_DEVICE_CHANGER"),
	_T("FILE_DEVICE_SMARTCARD"),
	_T("FILE_DEVICE_ACPI"),
	_T("FILE_DEVICE_DVD"),
	_T("FILE_DEVICE_FULLSCREEN_VIDEO"),
	_T("FILE_DEVICE_DFS_FILE_SYSTEM"),
	_T("FILE_DEVICE_DFS_VOLUME"),
	_T("FILE_DEVICE_SERENUM"),
	_T("FILE_DEVICE_TERMSRV"),
	_T("FILE_DEVICE_KSEC")
};
#define METHOD_COUNT 4
TCHAR * methods[METHOD_COUNT] = {
	_T("METHOD_BUFFERED"),
	_T("METHOD_IN_DIRECT"),
	_T("METHOD_OUT_DIRECT"),
	_T("METHOD_NEITHER")
};
#define ACCESS_COUNT 4
TCHAR * access[ACCESS_COUNT] = {
	_T("FILE_ANY_ACCESS"),
	_T("FILE_READ_DATA"),
	_T("FILE_WRITE_DATA"),
	_T("FILE_READ_DATA | FILE_WRITE_DATA")
};